    <?php
    if (!isset($_SESSION['cli_id'])) {
        header('location:/identifica');
    }
    ?>
    <form action="/pedido" method="POST" id="formMenu">
        <section id="listaProdutos" class="my-5">
            <div class="container-fluid">
                <!-- cardápio -->
                <div class="row d-flex justify-content-center">

                    <!-- Menu cardápio -->
                    <div class="col-12 col-md-8 px-0">

                        <nav class="navbar sticky-top navbar-expand bg-dark text-white rounded-top mx-0" id="menuOptions">
                            <ul class="navbar-nav w-100 d-flex justify-content-around">
                                <li class="active nav-item ListMenu" onclick="showOption('showLanches')">
                                    <a name="lanche" type="button" class="nav-link text-white optList">
                                        Lanches
                                        <i class="fas fa-caret-down fas-2x text-white"></i>
                                    </a>
                                </li>
                                <li class="nav-item ListMenu" onclick="showOption('showPorcoes')">
                                    <a name="lanche" type="button" class="nav-link text-white optList">
                                        Porções
                                        <i class="fas fa-caret-down text-white"></i>
                                    </a>
                                </li>
                                <li class="nav-item ListMenu" onclick="showOption('showBebidas')">
                                    <a name="bebida" type="button" class="nav-link text-white optList">
                                        Bebidas
                                        <i class="fas fa-caret-down text-white"></i>
                                    </a>
                                </li>
                            </ul>
                        </nav>

                    </div>
                    <!-- Fim Menu cardápio -->

                    <!-- Lista de produtos -->
                    <div class="container-fluid">
                        <div class="row d-flex justify-content-center mb-4">
                            <div class="col-12 col-md-8 bg-white rounded-bottom">

                                <!-- Lanches -->
                                <div class="d-none" id="showLanches">

                                    <!-- Listagem de lanches do DB-->

                                    <div class="row rounded p-3 border-bottom">
                                        <div class="col-6 border-right">

                                            <div class="row d-flex justify-content-center">
                                                <h4>X calabresa</h4>
                                            </div>
                                            <div class="row text-center d-flex justify-content-center">
                                                <label for="1">
                                                    <img class="align-self-center border-bottom" src="http://guiabotucatu.com/public/Promocoes/2266/Promocao_201604250326298462d3ef9f92300092a34b211e303c1b.jpg" alt="" width="150" height="100">
                                                </label>
                                            </div>
                                            <div class="row text-center">
                                                <p class="text-secondary">Pão de lanche, maionese da casa, alface, tomate, queijo mussarela, Calabresa e cabola</p>
                                            </div>
                                        </div>
                                        <div class="col-6">
                                            <div class="row d-flex justify-content-center">
                                                <h4 class="text-danger">R$ 16,00</h4>
                                            </div>
                                            <div class="row d-flex justify-content-center">
                                                <div class="form-group">
                                                    <label for="1">Quero esse
                                                        <input type="checkbox" name="prod_id" value="1" id="1" class="form-control">
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="row d-flex justify-content-center">
                                                <div class="form-group">
                                                    <label for="">Quantidade:
                                                        <input type="number" name="qtd_lanche1" min="0" max="5" step="1" class="form-control" placeholder="1-5">
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <!-- Fim Listagem de lanches do DB-->

                                    <div class="row rounded p-3 border-bottom">
                                        <div class="col-6 border-right">

                                            <div class="row d-flex justify-content-center">
                                                <h4>X Bacon</h4>
                                            </div>
                                            <div class="row text-center d-flex justify-content-center">
                                                <label for="2">
                                                    <img class="align-self-center" src="https://www.pngkey.com/png/full/9-91496_x-bacon-png-lanches-x-bacon-png.png" alt="" width="150" height="100">
                                                </label>
                                            </div>
                                            <div class="row text-center">
                                                <p class="text-secondary ">Pão de lanche, maionese da casa, alface, tomate, hamburguer 90mg da casa, queijo cheddar, Bacon em tiras</p>
                                            </div>
                                        </div>
                                        <div class="col-6">
                                            <div class="row d-flex justify-content-center">
                                                <h4 class="text-danger">R$ 18,00</h4>
                                            </div>
                                            <div class="row d-flex justify-content-center">
                                                <div class="form-group">
                                                    <label for="2">Quero esse
                                                        <input type="checkbox" name="prod_id2" value="2" id="2" class="form-control">
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="row d-flex justify-content-center">
                                                <div class="form-group">
                                                    <label for="">Quantidade:
                                                        <input type="number" name="qtd_lanche2" min="0" max="5" step="1" class="form-control" placeholder="1-5">
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <!-- Porçoes -->
                                <div class="d-none" id="showPorcoes">

                                    <!-- Listagem de Porções do DB-->
                                    <div class="row rounded p-2 border-bottom">
                                        <div class="col-6 border-right">
                                            <div class="row d-flex justify-content-center border-bottom p-2">
                                                <h4 class="mt-1">Batata Frita</h4>
                                            </div>
                                            <div class="row text-center d-flex justify-content-center p-3">
                                                <img class="img-fluid" src="https://www.mammabia.com.br/uploads/img/550/porcao-de-batatas-fritas_2471a3119761ea248678f9dfaadff53c.jpg" alt="" width="250" height="200">
                                            </div>
                                        </div>

                                        <div class="col-6">
                                            <div class="row d-flex justify-content-center text-center">
                                                <table class="table">
                                                    <thead>
                                                        <td class="border-right">
                                                            <h5 class="text-danger">R$ 16,00</h5>
                                                        </td>
                                                    </thead>
                                                    <tr class="border-bottom">
                                                        <td class="border-right">
                                                            <input type="checkbox" name="prod_id3" value="3" id="3" class="form-control">
                                                        </td>
                                                    </tr>
                                                </table>
                                            </div>
                                            <div class="row d-flex justify-content-center">
                                                <h4 class="text-danger">Quantidade</h4>
                                            </div>

                                            <div class="row d-flex justify-content-center">
                                                <div class="form-group">
                                                    <label for="">
                                                        <input type="number" name="qtd_porcao3" min="0" max="5" step="1" class="form-control" placeholder="1-5">
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row rounded p-2 border-bottom">
                                        <div class="col-6 border-right">
                                            <div class="row d-flex justify-content-center p-2 border-bottom">
                                                <h4 class="mt-1">Frango Empanado</h4>
                                            </div>
                                            <div class="row text-center d-flex justify-content-center">
                                                <img class="align-self-center" src="https://www.kerokery.com.br/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/k/k/kkr-_152-sku-413___por_es__isca-de-frango.jpg" alt="" width="220" height="190"> </label>
                                            </div>
                                        </div>

                                        <div class="col-6">
                                            <div class="row d-flex justify-content-center text-center">
                                                <table class="table">
                                                    <thead>
                                                        <td>
                                                            <h5 class="text-danger">R$ 18,00</h5>
                                                        </td>
                                                    </thead>
                                                    <tr class="border-bottom">
                                                        <td class="border-right">
                                                            <input type="checkbox" name="prod_id4" value="4" id="4" class="form-control">
                                                        </td>
                                                    </tr>
                                                </table>
                                            </div>
                                            <div class="row d-flex justify-content-center">
                                                <h4 class="text-danger">Quantidade</h4>
                                            </div>

                                            <div class="row d-flex justify-content-center">
                                                <div class="form-group">
                                                    <label for="">
                                                        <input type="number" name="qtd_porcao4" min="0" max="5" step="1" class="form-control" placeholder="1-5">
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <!-- Bebidas -->
                                <div class="d-none" id="showBebidas">
                                    <div class="row rounded p-3 border-bottom">
                                        <div class="col-6 border-right">

                                            <div class="row d-flex justify-content-center">
                                                <h4>Coca lata 390 ml</h4>
                                            </div>
                                            <div class="row text-center d-flex justify-content-center">
                                                <label for="5">
                                                    <img class="align-self-center" src="https://trimais.vteximg.com.br/arquivos/ids/970793-1000-1000/foto_original.jpg?v=637135150340070000" alt="" width="200" height="170">
                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-6">
                                            <div class="row d-flex justify-content-center">
                                                <h4 class="text-danger">R$ 6,00</h4>
                                            </div>
                                            <div class="row d-flex justify-content-center">
                                                <div class="form-group">
                                                    <label for="5">Quero esse
                                                        <input type="checkbox" name="prod_id5" value="5" id="5" class="form-control">
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="row d-flex justify-content-center">
                                                <div class="form-group">
                                                    <label for="">Quantidade:
                                                        <input type="number" name="qtd_bebida5" min="0" max="5" step="1" class="form-control" placeholder="1-5">
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row rounded p-3 border-bottom">
                                        <div class="col-6 border-right">

                                            <div class="row d-flex justify-content-center">
                                                <h4>Coca Cola 600 ml</h4>
                                            </div>
                                            <div class="row text-center d-flex justify-content-center">
                                                <label for="6">
                                                    <img class="align-self-center" src="https://ibassets.com.br/ib.item.image.big/b-2654575009194e15a9475306f1f8c0ec.jpeg" alt="" width="200" height="170">
                                                </label>
                                            </div>
                                        </div>
                                        <div class="col-6">
                                            <div class="row d-flex justify-content-center">
                                                <h4 class="text-danger">R$ 8,00</h4>
                                            </div>
                                            <div class="row d-flex justify-content-center">
                                                <div class="form-group">
                                                    <label for="6">Quero esse
                                                        <input type="checkbox" name="prod_id6" value="6" id="6" class="form-control">
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="row d-flex justify-content-center">
                                                <div class="form-group">
                                                    <label for="">Quantidade:
                                                        <input type="number" name="qtd_bebida6" min="0" max="5" step="1" class="form-control" placeholder="1-5">
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row rounded p-3 border-bottom">
                                        <div class="col-6 border-right">

                                            <div class="row d-flex justify-content-center">
                                                <h4>Coca Cola 1,5 L</h4>
                                            </div>
                                            <div class="row text-center d-flex justify-content-center">
                                                <label for="BebidaId7">
                                                    <img class="align-self-center" src="https://www.superemkasa.com.br/fotos/extragrande/20398fe1/refrigerante-coca-cola-1-5l.jpg" alt="" width="200" height="170">
                                                </label>

                                            </div>

                                        </div>
                                        <div class="col-6">
                                            <div class="row d-flex justify-content-center">
                                                <h4 class="text-danger">R$ 10,00</h4>
                                            </div>
                                            <div class="row d-flex justify-content-center">
                                                <div class="form-group">
                                                    <label for="7">Quero esse
                                                        <input type="checkbox" name="prod_id7" value="7" id="7" class="form-control">
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="row d-flex justify-content-center">
                                                <div class="form-group">
                                                    <label for="">Quantidade:
                                                        <input type="number" name="qtd_bebida7" min="0" max="5" step="1" class="form-control" placeholder="1-5">
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <!--Fim  Lista de produtos -->

                        </div>

                        <div class="row d-flex justify-content-center">
                            <div class="col-12 col-md-8 d-flex justify-content-center">
                                <button type="button" class="btn btn-danger w-50" onclick="showDiv('enderecoEntrega','listaProdutos')">
                                    Continuar
                                </button>
                            </div>
                        </div>

                        <!-- Fim cardápio -->
                    </div>

        </section>

        <!-- Inicio identificação -->
        <section id="enderecoEntrega" class="d-none">
            <div class="container">
                <div class="row mb-3 text-center">
                    <div class="col-12 border-bottom">
                        <h3 class="text-white">Dados para entrega</h3>
                    </div>
                </div>
                <div class="row d-flex justify-content-center">

                    <div class="col-8">
                        <input type="text" name="cli_name" class="form-control text-secondary" placeholder="Digite seu nome">
                    </div>
                    <div class="col-4">
                        <select name="cli_city" class="form-control text-secondary ">
                            <option disabled selected>Cidade</option>
                            <option value="1">Salto</option>
                            <option value="2">ITU</option>
                            <option value="3">Indaíatuba</option>
                        </select>
                    </div>

                </div>
                <div class="row d-flex justify-content-center my-3">
                    <div class="col-9">
                        <input type="text" name="cli_street" class="form-control text-secondary" placeholder="Digite a rua">
                    </div>

                    <div class="col-3">
                        <input type="text" name="cli_n_house" placeholder="Nº " class="form-control text-secondary">
                    </div>
                </div>
                <div class="row d-flex justify-content-center">


                    <div class="col-12">
                        <input type="text" name="cli_district" class="form-control text-secondary" placeholder="Bairro">
                    </div>
                    <div class="col-12 mt-3">
                        <textarea name="cli_obs" class="form-control text-secondary" placeholder="Deixe alguma obervação, como apartamento, casa dos fundos, etc..."></textarea>
                    </div>

                </div>
            </div>
            <div class="container">
                <div class="row mt-3 d-flex justify-content-around">
                    <div class="col-6 col-md-4">
                        <button type="button" class="form-control btn btn-danger" onclick="showDiv('listaProdutos','enderecoEntrega')">
                            Voltar
                        </button>
                    </div>
                    <div class="col-6 col-md-4">
                        <button type="submit" class="form-control btn btn-danger">
                            Continuar
                        </button>
                    </div>
                </div>
            </div>
        </section><!-- Fim identificação -->

    </form>